### ISSUE TITLE
Create a `themes` directory first.

### ISSUE THREAD

**Issue by SupianIDz** [SadeghPouriyanZadeh/minty-dracula#1]
https://github.com/SadeghPouriyanZadeh/minty-dracula/blob/adf66ac5149e274e13f28d1c8c2e326c41b54cd1/grub.sh#L6

The `themes` directory in some Distros is not available and this will cause an error when copying, create a `themes` directory first.

**Comment by sadegh-pz** [comment]
I have done this. Thanks a lot for informing me.
